### ISSUE TITLE
Fabs function not declar in this scope

### ISSUE THREAD

**Issue by amrkamal2025** [oyvindln/jumpDesktop#1]
I got this error when i compile the project using QT 5.12.0 Mingw32 or 64

` 'fabs' was not declared in this scope        (100.0 - fabs(m_players[m_playerNumber]->getBalance()) * 2) / 100.0);`

**Comment by oyvindln** [comment]
Sorry for taking some time to reply.
I'll sort it soon, it should be simple to fix.

**Comment by oyvindln** [comment]
Don't have a windows compile environment set up right now, but f9342c0 fixes this for me on linux at least.
@amrkamal2025  Does it compile fine with mingw with that commit as well?

**Comment by amrkamal2025** [comment]
Thank you very it worked
